version: "3"
services:
 my_app:
  image: 340482407314.dkr.ecr.us-east-1.amazonaws.com/intro_app:latest
  ports:
   - 3000:3000
  restart: always

 mongo_db:
  image: mongo
  restart: always
  ports:
   - 27017:27017
  volumes:
   - app-data:/data/db
 mongo-express:
  image: mongo-express:1.0.2-20-alpine3.19
  restart: always
  ports:
   - 8081:8081
  environment:
   ME_CONFIG_MONGODB_URL: mongodb://mongo_db:27017/
   ME_CONFIG_BASICAUTH_ENABLED: true
   ME_CONFIG_BASICAUTH_USERNAME: admin
   ME_CONFIG_BASICAUTH_PASSWORD: pass

volumes:
 app-data: